Challenge 12 completed
CappaCoppa/be_nc_games pull request #11
Opened 2022-05-20 14:20 UTC by CappaCoppa

2022-05-20 14:34 UTC, mallionaire requested changes
You'll need to add test cases for: 
 - 404 comment not found
 - 400 invalid comment id

2022-05-20 14:34 UTC, mallionaire commented on __tests__/app.test.js
> +            console.log(res.body)
remove console.logs

2022-05-20 14:34 UTC, mallionaire commented on controllers/categories.controller.js
> +        console.log(deletedComment)
remove

2022-05-20 14:55 UTC, mallionaire requested changes
Still some console.logs in here, you'll need to remove them before it can be approved

2022-05-23 15:10 UTC, scar1377 commented on __tests__/app.test.js
> +            expect(Object.keys(res.body).length).toEqual(0)
don't need the .then() block

2022-05-23 15:10 UTC, scar1377 commented on controllers/categories.controller.js
> +            return Promise.reject({status: 404, msg : "comment_id in path but does not exist"})
This part is better in the model. only leave.then in controller

2022-05-23 15:10 UTC, scar1377 commented on models/categories.model.js
> +    return db.query("DELETE FROM comments WHERE comment_id = $1 RETURNING *",[id]).then(({rows})=>{
can take a look at rowCount rather than rows. When It's 0, return Promise.reject

2022-05-24 13:11 UTC, scar1377 approved these changes
Good to merge

2022-05-24 19:26 UTC, merged